---
version: 2
updates:
  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: monthly
    reviewers:
      - nacl30d

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    reviewers:
      - nacl30d
